config/routes.rb
MDManage::Application.routes.draw do
  get "archives/index"
  get "archives/users"
  get "archives/clients"
  get "archives/patients"
  get "archives/accidents"
  get "archives/chiropractic_examinations"
  get "archives/chiropractic_treatments"
  get "archives/insurance_companies"
  
  get "reports/index"
  get "reports/weekly_summary"
  get "reports/monthly_summary"

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :insurance_companies
  
  resources :patients do
    delete "remove"
    resources :accidents do
      resources :chiropractic_examinations do
        member do
          get 'insurance_claim_processed'
          get 'print_friendly'
        end
        
        resource :chiropractic_symptom_list
        resource :chiropractic_investigation_list
        resource :chiropractic_diagnosis_list
        resource :chiropractic_treatment_plan
        resource :chiropractic_assessment
        resource :chiropractic_compliance
        
        resources :chiropractic_treatments do
          member do
            get 'insurance_claim_processed'
            get 'print_friendly'
          end
          
          resource :chiropractic_observation_list
          resource :chiropractic_body_adjustment_list
          resource :chiropractic_modalities_list
        end
      end
    end
  end

  resources :users do
    collection do
      get 'new_external'
      get 'doctor_dashboard'
    end
    
    member do
      get 'ignore_re_examination_reminders'
    end
  end
  
  resources :clients do
    member do
      get 'pending_examinations'
      get 'completed_examinations'
      get 'processed_examinations'
      get 'pending_treatments'
      get 'completed_treatments'
      get 'processed_treatments'
      get 'users'
    end
  end
  
  resources :roles
  resources :sessions
  resources :password_resets
  

  root :to => "sessions#new"

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation, :role_id, :client_id, :digital_signature
  
  has_secure_password
  
  validates_presence_of :password, :on => :create
  validates_presence_of :name
  
  validates :email, :presence => true, 
                    :uniqueness => true, 
                    :format => {:with => /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i}
  
  belongs_to :role
  belongs_to :client
  
  has_attached_file :digital_signature, :styles => { :short => "200x30>" }
  validates_attachment_content_type :digital_signature, :content_type => /\Aimage\/.*\Z/
    
  def admin?
    self.role.name == 'Admin'
  end
  
  def staff?
    self.role.name == 'Staff'
  end
  
  def front_desk?
    self.role.name == 'FrontDesk'
  end
  
  def doctor?
    self.role.name == 'Doctor'
  end
  
  def in_house_user?
    self.admin? || self.staff?
  end
  
  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    
    UserMailer.password_reset(self).deliver
  end
  
  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :login_required
  before_filter :set_current_tab
  before_filter :check_for_mobile
  
  # GET /users
  # GET /users.json
  def index
    @users = User.not_deleted.where(:client_id => nil).order(:role_id, :name).page(params[:page]).per(15)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end
  
  def new
    @user = User.new
  end

  def new_external
    session[:current_tab] = 'Clients'
    @client = Client.find(params[:client_id])
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to users_path, :notice => "Signed up!"  if @user.client.blank?
      redirect_to users_client_path(@user.client), :notice => "Signed up!" if @user.client
    else
      render "new" if @user.client.blank?
      render "new_external" if @user.client
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end
  
  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])
    @user.digital_signature = nil if params[:remove_digital_signature]
    
    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { 
          redirect_to users_url, notice: 'User was successfully updated.' if @user.client.blank?
          redirect_to users_client_path(@user.client), :notice => "User was successfully updated" if @user.client
        }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    client = @user.client
    
    if @user.deleted_at.blank?
      @user.destroy
    else
      @user.revive
    end
    
    respond_to do |format|
      format.html { 
        if session[:current_tab] == 'Archives'
          redirect_to archives_users_path
        elsif client.blank?
          redirect_to users_path
        else
          redirect_to users_client_path(client)
        end
      }
      format.json { head :ok }
    end
  end
  
  #GET /users/doctor_dashboard(.:format)
  def doctor_dashboard
    session[:current_tab] = 'Dashboard'
    @client = current_user.client
    
    @pending_chiropractic_treatments = ChiropracticTreatment.not_deleted.where(:client_id => @client.id, :completed => false)
    @pending_chiropractic_examinations = ChiropracticExamination.not_deleted.where(:client_id => @client.id, :completed => false)
    
    # http://www.freeopenbook.com/mysqlcookbook/mysqlckbk-chp-12-sect-6.html
    @new_patients = Patient.where(:client_id => @client.id).order('created_at DESC').limit(50).select { |patient| patient.chiropractic_examinations.blank? }
    
    # http://www.freeopenbook.com/mysqlcookbook/mysqlckbk-chp-12-sect-7.html
    accident_ids = @client.chiropractic_examinations.not_deleted.select("accident_id, max(examination_date) as last_examination_date").group("accident_id").having("last_examination_date < ?", Date.today - 28.days).collect { |chiropractic_examination| chiropractic_examination.accident_id }
    accidents = Accident.includes(:patient).find(accident_ids)
    @reminder_patients = accidents.collect { |accident| accident.patient.decorate }
    @reminder_patients.select! {|patient| !patient.ignore_re_examination_reminders}#.sort_by { ||}
  end
  
  # GET /users/1/ignore_re_examination_reminders(.:format)
  def ignore_re_examination_reminders
    user = User.find(params[:id])
    user.ignore_re_examination_reminders = true
    user.save!
    redirect_to doctor_dashboard_users_path
  end
  
  private
  
  def set_current_tab
    session[:current_tab] = 'Users' unless session[:current_tab] == 'Archives'
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/doctor_dashboard.html.erb
<p style="text-transform:uppercase; font-weight:bold; font-size:12px;">New Patients</p>

<div class="span-24">	
	<table class="advanced">
	  <thead>
	    <th class="span-4">Name</th>
	    <th class="span-2">Age</th>
	    <th class="span-3">Cell Phone</th>
	    <th class="span-4">Occupation</th>
	    <th class="span-2">Handed</th>
			<th class="span-2">Height</th>
			<th class="span-2">Weight</th>
			<th class="span-5"></th>
    </thead>

		<tbody>
			<% @new_patients.each do |patient| %>
			  <tr>
			    <td><%= patient.full_name %></td>
			    <td><%= patient.age %> yrs</td>
			    <td><%= patient.cell_phone %></td>
			    <td><%= patient.occupation %></td>
			    <td><%= patient.handed %></td>
			    <td><%= patient.height %> </td>
			    <td><%= patient.weight %> lbs</td>
			    <td><%= link_to 'Show', patient_path(patient) %> | <%= link_to 'Edit', edit_patient_path(patient) %> | <%= link_to 'Archive', patient, confirm: 'Are you sure you want to archive this patient?', method: :delete %> | <%= link_to 'Delete', patient_remove_path(patient), confirm: 'Are you sure you want to delete this patient?', method: :delete %>
					<% if current_user.doctor? %>
				 		| <%= (patient.accidents.blank?) ? link_to('New Case', new_patient_accident_path(patient)) : link_to('Cases', patient_accidents_path(patient)) %>
					<% end %>
					</td>
			  </tr>
			<% end %>
		</tbody>
		
		<tfoot>
			<tr>
				<td colspan="8" class="quiet"><center>The initial chiropractic examination is not yet done for these patients.</center></td>
			</tr>
		</tfoot>
	</table>

</div>

<hr/>
<hr class="space"/>

<p style="text-transform:uppercase; font-weight:bold; font-size:12px;">Re-examination Reminders</p>

<div class="span-24">	
	<table class="advanced">
	  <thead>
	    <th class="span-4">Name</th>
	    <th class="span-2">Age</th>
	    <th class="span-2">Gender</th>
	    <th class="span-4">Occupation</th>
	    <th class="span-2">Handed</th>
			<th class="span-2">Height</th>
			<th class="span-2">Weight</th>
			<th class="span-6"></th>
    </thead>

		<tbody>
			<% @reminder_patients.each do |patient| %>
			  <tr>
			    <td><%= patient.full_name %></td>
			    <td><%= patient.age %> yrs</td>
			    <td><%= patient.gender %></td>
			    <td><%= patient.occupation %></td>
			    <td><%= patient.handed %></td>
			    <td><%= patient.height %> inches</td>
			    <td><%= patient.weight %> lbs</td>
			    <td><%= link_to 'Show', patient_path(patient) %> | <%= link_to 'Edit', edit_patient_path(patient) %> | <%= link_to 'Archive', patient, confirm: 'Are you sure you want to archive this patient?', method: :delete %> | <%= link_to 'Ignore', ignore_re_examination_reminders_user_path(patient), confirm: 'Are you sure you want to ignore re-examination reminders for this patient?' %>
					<% if current_user.doctor? %>
				 		| <%= (patient.accidents.blank?) ? link_to('New Case', new_patient_accident_path(patient)) : link_to('Cases', patient_accidents_path(patient)) %>
					<% end %></td>
			  </tr>
			<% end %>
		</tbody>
		
		<tfoot>
			<tr>
				<td colspan="8" class="quiet"><center>Last examination was done at least a month ago for these patients.</center></td>
			</tr>
		</tfoot>
	</table>

</div>

<hr/>
<hr class="space"/>

<p style="text-transform:uppercase; font-weight:bold; font-size:12px;">Pending Chiropractic Examinations</p>

<div class="span-24">	
	<table class="advanced">
	  <thead>
		<th class="span-4">Patient</th>
		<th class="span-4">Examination Date</th>
		<th class="span-4">Re-examination</th>
    <th class="span-5 last"></th>
  </thead>

	<tbody>
		<% @pending_chiropractic_examinations.each do |chiropractic_examination| %>
			<% accident = chiropractic_examination.accident %>
			<% patient = accident.patient %>
		  <tr>
				<td><%= patient.full_name %></td>
				<td><%= chiropractic_examination.examination_date.strftime('%b %d, %Y') %></td>
				<td><%= chiropractic_examination.initial_examination? ? 'No' : 'Yes' %></td>
		    <td><%= link_to 'Show', patient_accident_chiropractic_examination_path(patient, accident, chiropractic_examination) %> | 	<%= link_to 'Edit', edit_patient_accident_chiropractic_examination_path(patient, accident, chiropractic_examination) %> |	<%= link_to 'Archive', patient_accident_chiropractic_examination_path(patient, accident, chiropractic_examination), confirm: 'Are you sure you want to archive this examination? All related treatment notes will also be archived.', method: :delete %> </td>
		  </tr>
		<% end %>
	</tbody>	
	
	<tfoot>
		<tr>
			<td colspan="4" class="quiet"><center>Chiropractic examination form was partially filled for these patients.</center></td>
		</tr>
	</tfoot>
</table>

<hr/>
<hr class="space"/>

<p style="text-transform:uppercase; font-weight:bold; font-size:12px;">Pending Chiropractic Treatments</p>

<div class="span-24">	
	<table class="advanced">
	  <thead>
			<th class="span-4">Patient</th>
			<th class="span-4">Treatment Date</th>
			<th class="span-4"></th>
      <th class="span-5 last"></th>
  </thead>
	
	<tbody>
		<% @pending_chiropractic_treatments.each do |chiropractic_treatment| %>
			<% chiropractic_examination = chiropractic_treatment.chiropractic_examination %>
			<% accident = chiropractic_examination.accident %>
			<% patient = accident.patient %>
		  <tr>
		    <td><%= patient.full_name %></td>
		    <td><%= chiropractic_treatment.treatment_date.strftime('%b %d, %Y') %></td>
				<td>&nbsp;</td>
		    <td><%= link_to 'Show', patient_accident_chiropractic_examination_chiropractic_treatment_path(patient, accident, chiropractic_examination, chiropractic_treatment) %> | <%= link_to 'Edit', edit_patient_accident_chiropractic_examination_chiropractic_treatment_path(patient, accident, chiropractic_examination, chiropractic_treatment) %> | <%= link_to 'Archive', patient_accident_chiropractic_examination_chiropractic_treatment_path(patient, accident, chiropractic_examination, chiropractic_treatment), confirm: 'Are you sure you want to archive this chiropractic treatment record?', method: :delete %></td>
		  </tr>
		<% end %>
	</tbody>
	
	<tfoot>
		<tr>
			<td colspan="3" class="quiet"><center>Chiropractic treatment form was partially filled for these patients.</center></td>
		</tr>
	</tfoot>
</table>

<hr/>
<hr class="space"/>

app/views/users/edit.html.erb
<div class="span-24">

<%= form_for @user do |f| %>

  <%= render "shared/error_messages", :target => @user %>

	<div class="span-24">
		<div class="span-12">
			<%= f.label :name %><br />
	    <%= f.text_field :name, :class => 'title' %>
		</div>
		<div class="span-12 last">
			<%= f.label :email %><br />
	    <%= f.text_field :email, :class => 'title' %>
		</div>
	</div>
	
	<hr class="space"/>
	
	<a href="javascript:togglePasswordFields();" class="button" id="toggle_link">Change Password</a>
	
	<hr class="space"/>
	
	<div class="span-24" id="password_fields" style="display:none;">
		<div class="span-12">
			<%= f.label :password %><br />
	    <%= f.password_field :password, :class => 'title' %>
		</div>
		<div class="span-12 last">
			<%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, :class => 'title' %> <br/>
		</div>
		<span class="quiet">* If you leave the password fields blank, the user's current password is not changed. Enter a new password and confirmation, if you want to change the password for this user.</span>
		<hr class="space"/>
	</div>

	<div class="span-24">
		<%= f.label :digital_signature %><br />
		<%= f.file_field :digital_signature %>
	</div>
	
	<% if @user.digital_signature.exists? %>
		<hr class="space"/>
		
		<div class="span-24">
			<%= image_tag @user.digital_signature.url(:short) %> <br/>
			<%= check_box_tag :remove_digital_signature %>&nbsp;Remove digital signature
		</div>
	
	<% end %>
	
	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-3">
			<%= link_to 'Back', users_path, :class => 'button' %>
		</div>
		<div class="prepend-15 span-3 last">
				<br/>
	    	<%= f.submit %>
		</div>
  </div>

<% end %>

</div>

<script type="text/javascript" charset="utf-8">
	function togglePasswordFields() {
		$("#password_fields").toggle();
		
		if ($("#password_fields").is(":visible")) {
			$("#toggle_link").text('Hide Password Fields');
		} else {
			$("#toggle_link").text('Change Password');
		}
	}
</script>

app/views/users/index.html.erb
<div class="span-24">	
	<table class="advanced">
	  <thead>
    <th class="span-9">Name</th>
    <th class="span-6">E-mail</th>
    <th class="span-4">Role</th>
		<th class="span-5 last"></th>
  </thead>

	<% @users.each do |user| %>
 	 	<tr>
	    <td><%= user.name %></td>
	    <td><%= user.email %></td>
	    <td><%= user.role.name %></td>
	    <td><%= link_to 'Edit', edit_user_path(user) %> | <%= link_to 'Archive', user, confirm: "Are you sure you want to archive this user?", method: :delete %></td>
	  </tr>
	<% end %>
	</table>
</div>

<hr class="space"/>

<div class="span-24">
	<%= paginate @users %>
</div>

<br/>

<div class="prepend-21 span-3">
	<%= link_to 'New User', new_user_path, :class => 'button positive' %>
</div>
	

app/views/users/new.html.erb
<div class="span-24">

<%= form_for @user do |f| %>

  <%= render "shared/error_messages", :target => @user %>

	<div class="span-24">
		<div class="span-12">
			<%= f.label :name %><br />
	    <%= f.text_field :name, :class => 'title' %>
		</div>
		<div class="span-12 last">
			<%= f.label :email %><br />
	    <%= f.text_field :email, :class => 'title' %>
		</div>
	</div>
	
	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-12">
			<%= f.label :password %><br />
	    <%= f.password_field :password, :class => 'title' %>
		</div>
		<div class="span-12 last">
			<%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, :class => 'title' %>
		</div>
	</div>
  
	<hr class="space"/>

	<div class="span-24">
		<%= f.label :role %><br />
		<%= f.collection_select(:role_id, Role.internal, :id, :name) %>
	</div>
	
	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-3">
			<%= link_to 'Back', users_path, :class => 'button' %>
		</div>
		<div class="prepend-15 span-3 last">
				<br/>
	    	<%= f.submit %>
		</div>
  </div>

<% end %>

</div>

app/views/users/new_external.html.erb
<div class="span-24">

<%= form_for @user do |f| %>

  <%= render "shared/error_messages", :target => @user %>

	<div class="span-24">
		<div class="span-12">
			<%= f.label :name %><br />
	    <%= f.text_field :name, :class => 'title' %>
		</div>
		<div class="span-12 last">
			<%= f.label :email %><br />
	    <%= f.text_field :email, :class => 'title' %>
		</div>
	</div>
	
	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-12">
			<%= f.label :password %><br />
	    <%= f.password_field :password, :class => 'title' %>
		</div>
		<div class="span-12 last">
			<%= f.label :password_confirmation %><br />
	    <%= f.password_field :password_confirmation, :class => 'title' %>
		</div>
	</div>
  
	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-12">
			<%= f.label :role %><br />
			<%= f.collection_select(:role_id, Role.external, :id, :name) %>
		</div>
		
		<div class="span-12 last">
			<%= f.label :client %><br />
			<%= @client.name %>
			<%= f.hidden_field :client_id, :value => @client.id %>
		</div>
	</div>
	
	<hr class="space"/>

	<div class="span-24">
		<%= f.label :digital_signature %><br />
		<%= f.file_field :digital_signature %>
	</div>
	
	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-3">
			<%= link_to 'Back', users_client_path(@client), :class => 'button' %>
		</div>
		<div class="prepend-15 span-3 last">
				<br/>
	    	<%= f.submit %>
		</div>
  </div>

<% end %>

</div>