config/routes.rb
MDManage::Application.routes.draw do
  get "archives/index"
  get "archives/users"
  get "archives/clients"
  get "archives/patients"
  get "archives/accidents"
  get "archives/chiropractic_examinations"
  get "archives/chiropractic_treatments"
  get "archives/insurance_companies"
  
  get "reports/index"
  get "reports/weekly_summary"
  get "reports/monthly_summary"

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :insurance_companies
  
  resources :patients do
    delete "remove"
    resources :accidents do
      resources :chiropractic_examinations do
        member do
          get 'insurance_claim_processed'
          get 'print_friendly'
        end
        
        resource :chiropractic_symptom_list
        resource :chiropractic_investigation_list
        resource :chiropractic_diagnosis_list
        resource :chiropractic_treatment_plan
        resource :chiropractic_assessment
        resource :chiropractic_compliance
        
        resources :chiropractic_treatments do
          member do
            get 'insurance_claim_processed'
            get 'print_friendly'
          end
          
          resource :chiropractic_observation_list
          resource :chiropractic_body_adjustment_list
          resource :chiropractic_modalities_list
        end
      end
    end
  end

  resources :users do
    collection do
      get 'new_external'
      get 'doctor_dashboard'
    end
    
    member do
      get 'ignore_re_examination_reminders'
    end
  end
  
  resources :clients do
    member do
      get 'pending_examinations'
      get 'completed_examinations'
      get 'processed_examinations'
      get 'pending_treatments'
      get 'completed_treatments'
      get 'processed_treatments'
      get 'users'
    end
  end
  
  resources :roles
  resources :sessions
  resources :password_resets
  

  root :to => "sessions#new"

end

app/views/shared/_admin_tabs.html.erb
<% reports_class = 'current' if session[:current_tab] == 'Reports' %>
<% clients_class = 'current' if session[:current_tab] == 'Clients' %>
<% users_class = 'current' if session[:current_tab] == 'Users' %>
<% insurance_companies_class = 'current' if session[:current_tab] == 'Insurance Companies' %>
<% archives_class = 'current' if session[:current_tab] == 'Archives' %>

<div class="invertedshiftdown">
	<ul>
		<li><%= link_to 'Logout', logout_path, :title => 'Logout' %></li>
		<li class="<%= archives_class %>"><%= link_to 'Archives', archives_index_path, :title => 'Archived Records' %></li>
		<li class='<%= insurance_companies_class %>'><%= link_to 'Insurance Companies', insurance_companies_path, :title => 'Insurance Companies' %></li>
		<li class='<%= reports_class %>'><%= link_to 'Reports', reports_index_path, :title => 'MIS Reports' %></li>
		<li class='<%= clients_class %>'><%= link_to 'Clients', clients_path, :title => 'Clients Database' %></li>
		<li class='<%= users_class %>'><%= link_to 'Users', users_path, :title => 'Users Database' %></li>
	</ul>
</div>

app/views/shared/_doctor_tabs.html.erb
<% dashboard_class = 'current' if session[:current_tab] == 'Dashboard' %>
<% patients_class = 'current' if session[:current_tab] == 'Patients' %>
<% completed_examinations_class = 'current' if session[:current_tab] == 'CompletedExaminations' %>
<% completed_treatments_class = 'current' if session[:current_tab] == 'CompletedTreatments' %>
<% archives_class = 'current' if session[:current_tab] == 'Archives' %>

<div class="invertedshiftdown">
	<ul>
		<li><%= link_to 'Logout', logout_path, :title => 'Logout' %></li>
		<li class="<%= archives_class %>"><%= link_to 'Archives', archives_index_path, :title => 'Archived Records' %></li>
		<li class="<%= completed_treatments_class %>"><%= link_to 'Completed Treatments', completed_treatments_client_path(@client), :title => 'Concluded Treatments List' %></li>
		<li class="<%= completed_examinations_class %>"><%= link_to 'Completed Examinations', completed_examinations_client_path(@client), :title => 'Concluded Examinations List' %></li>
		<li class="<%= patients_class %>"><%= link_to 'Patients', patients_path, :title => 'Patients Database' %></li>
		<li class="<%= dashboard_class %>"><%= link_to 'Dashboard', doctor_dashboard_users_path, :title => 'Dashboard' %></li>
	</ul>
</div>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
	<div class="span-20 error">
     <h4><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h4>

     <ul>
     <% target.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
     </ul>
  </div>
<% end %>

app/views/shared/_frontdesk_tabs.html.erb
<% patients_class = 'current' if session[:current_tab] == 'Patients' %>
<% archives_class = 'current' if session[:current_tab] == 'Archives' %>

<div class="invertedshiftdown">
	<ul>
		<li><%= link_to 'Logout', logout_path, :title => 'Logout' %></li>
		<li class="<%= archives_class %>"><%= link_to 'Archives', archives_index_path, :title => 'Archived Records' %></li>
		<li class="<%= patients_class %>"><%= link_to 'Patients', patients_path, :title => 'Patients Database' %></li>
	</ul>
</div>

app/views/shared/_site_footer.html.erb
<div class="span-24 non_printable_block">
	
	<hr class="space"/>
	<hr class="space"/>
	<hr class="space"/>

	<div class="quiet" style="text-align:center">
		All text and design is copyright &copy; 2005-2014 <a href="http://www.mdmanage.com" style="text-decoration:none;" target="_blank">MDManage</a>. All rights reserved.
	</div>

</div>

app/views/shared/_site_header.html.erb
<div class="span-24 non_printable_block">
	<div class="span-24">
			<%= link_to image_tag('logo.png'), root_url %>
	</div>

	<% if current_user %>

		<% if current_user.front_desk? || current_user.doctor? %>
			<div class="prepend-14 span-10">
				<%= form_tag patients_path, :method => 'get' do %>
				    <div class="span-4">
						<%= select_tag :filter, options_for_select([['First Name', 'first_name'], ['Last Name', 'last_name'], ['Social Security Number', 'social_security_number'], ['Cell Phone', 'cell_phone']], session[:filter]) %>
					</div>
					<div class="span-6 last">
						<%= text_field_tag :search, session[:search].blank? ? 'search for patient...' : session[:search], :class => 'search_field', :onFocus => "if(this.value == 'search for patient...') { this.value = ''; }", :onBlur => "if(this.value == '') { this.value = 'search for patient...'; }" %>
					</div>
				<% end %>
			</div>
		<% elsif current_user.staff? %>
		<div class="prepend-12 span-12">
			<%= form_tag clients_path, :method => 'get' do %>
     		  <div class="span-6">
				<%= select_tag :filter_client, options_for_select(Client.not_deleted.order('name').map{|c| ["Client - "+c.name, c.id]}, params[:filter_client]) %>
			  </div>
				<div class="span-6">
					<%= select_tag :filter, options_for_select([['Patient - First Name', 'first_name'], ['Patient - Last Name', 'last_name'], ['Patient - Social Security Number', 'social_security_number'], ['Patient - Cell Phone', 'cell_phone']], session[:filter]) %>
				</div>
				<div class="span-6 last">
					<%= text_field_tag :search, session[:search].blank? ? 'search for patient...' : session[:search], :class => 'search_field', :onFocus => "if(this.value == 'search for patient...') { this.value = ''; }", :onBlur => "if(this.value == '') { this.value = 'search for patient...'; }" %>
				</div>
			<% end %>
		</div>
		<% end %>
	
		<div class="span-24">
			<%= render :partial => "/shared/#{current_user.role.name.downcase}_tabs" %>
		</div>
	<% end %>

	<hr class="space"/>
</div>

app/views/shared/_staff_tabs.html.erb
<% clients_class = 'current' if session[:current_tab] == 'Clients' %>
<% insurance_companies_class = 'current' if session[:current_tab] == 'Insurance Companies' %>
<% archives_class = 'current' if session[:current_tab] == 'Archives' %>

<div class="invertedshiftdown">
	<ul>
		<li><%= link_to 'Logout', logout_path, :title => 'Logout' %></li>
		<li class="<%= archives_class %>"><%= link_to 'Archives', archives_index_path, :title => 'Archived Records' %></li>
		<li class='<%= insurance_companies_class %>'><%= link_to 'Insurance Companies', insurance_companies_path, :title => 'Insurance Companies' %></li>
		<li class='<%= clients_class %>'><%= link_to 'Clients', clients_path, :title => 'Clients Database' %></li>
	</ul>
</div>