config/routes.rb
MDManage::Application.routes.draw do
  get "archives/index"
  get "archives/users"
  get "archives/clients"
  get "archives/patients"
  get "archives/accidents"
  get "archives/chiropractic_examinations"
  get "archives/chiropractic_treatments"
  get "archives/insurance_companies"
  
  get "reports/index"
  get "reports/weekly_summary"
  get "reports/monthly_summary"

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :insurance_companies
  
  resources :patients do
    delete "remove"
    resources :accidents do
      resources :chiropractic_examinations do
        member do
          get 'insurance_claim_processed'
          get 'print_friendly'
        end
        
        resource :chiropractic_symptom_list
        resource :chiropractic_investigation_list
        resource :chiropractic_diagnosis_list
        resource :chiropractic_treatment_plan
        resource :chiropractic_assessment
        resource :chiropractic_compliance
        
        resources :chiropractic_treatments do
          member do
            get 'insurance_claim_processed'
            get 'print_friendly'
          end
          
          resource :chiropractic_observation_list
          resource :chiropractic_body_adjustment_list
          resource :chiropractic_modalities_list
        end
      end
    end
  end

  resources :users do
    collection do
      get 'new_external'
      get 'doctor_dashboard'
    end
    
    member do
      get 'ignore_re_examination_reminders'
    end
  end
  
  resources :clients do
    member do
      get 'pending_examinations'
      get 'completed_examinations'
      get 'processed_examinations'
      get 'pending_treatments'
      get 'completed_treatments'
      get 'processed_treatments'
      get 'users'
    end
  end
  
  resources :roles
  resources :sessions
  resources :password_resets
  

  root :to => "sessions#new"

end

app/models/accident.rb
class Accident < ActiveRecord::Base
  belongs_to :patient
  has_many :chiropractic_examinations, :dependent => :destroy

  def prior_diagnostic_study_mri_details=(attr)
    self.prior_diagnostic_study_mri = attr.join("--")
  end
  
  def prior_diagnostic_study_mri_details
    (self.prior_diagnostic_study_mri || "").split("--")
  end
  
  def prior_diagnostic_study_ctscan_details=(attr)
    self.prior_diagnostic_study_ctscan = attr.join("--")
  end
  
  def prior_diagnostic_study_ctscan_details
    (self.prior_diagnostic_study_ctscan || "").split("--")
  end
  
  def prior_diagnostic_study_emg_details=(attr)
    self.prior_diagnostic_study_emg = attr.join("--")
  end
  
  def prior_diagnostic_study_emg_details
    (self.prior_diagnostic_study_emg || "").split("--")
  end
end

app/controllers/accidents_controller.rb
class AccidentsController < ApplicationController
  before_filter :login_required
  before_filter :load_client_and_patient
  before_filter :check_for_mobile
  
  # GET /patients/:patient_id/accidents(.:format)
  def index
    @accidents = @patient.accidents.not_deleted.order('created_at desc').page(params[:page]).per(5)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @accidents }
    end
  end

  # GET /patients/:patient_id/accidents/:id(.:format)
  def show
    @accident = @patient.accidents.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @accident }
    end
  end

  # GET /patients/:patient_id/accidents/new(.:format)
  def new
    @accident = @patient.accidents.build
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @accident }
    end
  end

  # GET /patients/:patient_id/accidents/:id/edit(.:format)
  def edit
    @accident = @patient.accidents.find(params[:id])
  end

  # POST /patients/:patient_id/accidents(.:format)
  def create
    @accident = @patient.accidents.build(params[:accident])
        
    respond_to do |format|
      if @accident.save
        format.html { redirect_to patient_accident_path(@patient, @accident), notice: 'Case was successfully created.' }
        format.json { render json: @accident, status: :created, location: @accident }
      else
        format.html { render action: "new" }
        format.json { render json: @accident.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/:patient_id/accidents/:id(.:format)
  def update
    @accident = @patient.accidents.find(params[:id])    
    
    respond_to do |format|
      if @accident.update_attributes(params[:accident])
        format.html { redirect_to patient_accident_path(@patient, @accident), notice: 'Case was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @accident.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/:patient_id/accidents/:id(.:format)
  def destroy
    @accident = Accident.find(params[:id])
    
    if @accident.deleted_at.blank?
      @accident.destroy
    else
      @accident.revive
    end
    
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :ok }
    end
  end
  
  private
  
  def load_client_and_patient
    session[:current_tab] = 'Patients' unless session[:current_tab] == 'Archives'
    
    if current_user.admin? || current_user.staff?
      @client = Patient.find(params[:patient_id]).client
    else
      @client = Client.find(current_user.client_id)
    end
    
    @patient = @client.patients.find(params[:patient_id])
  end
end

app/helpers/accidents_helper.rb
module AccidentsHelper
end

app/views/accidents/_chiropractic_examination.html.erb
<tr>
  <td colspan="4">
		<% 3.times do %>
			&nbsp;
		<% end %>
		<a href="#" onclick="$('.daily_treatment_notes_<%= chiropractic_examination.id %>').toggle(); toggle_disclosure_triangle($(this).find('#disclosure_triangle')); return false;"><%= image_tag('triangle_right.png', :id => 'disclosure_triangle') %></a>
	<%= link_to chiropractic_examination.initial_examination? ? 'Initial Examination' : 'Re-examination',  patient_accident_chiropractic_examination_path(patient, accident, chiropractic_examination) %> 
	<% unless chiropractic_examination.examination_date.blank? %>
		on <%= chiropractic_examination.examination_date.strftime('%b %d, %Y') %>
	<% else %>
		in progress
	<% end %>	
	<% unless chiropractic_examination.summary.blank? %>
	 - <%= chiropractic_examination.summary %>
	<% end %>
	</td>
</tr>

<%= render(:partial => "chiropractic_treatment", :collection => chiropractic_examination.chiropractic_treatments, :locals => {:patient => @patient, :accident => accident, :chiropractic_examination => chiropractic_examination} ) %>

app/views/accidents/_chiropractic_treatment.html.erb
<tr class="daily_treatment_notes_<%= chiropractic_examination.id %>" style="display:none;">
  <td colspan="4">
		<% 6.times do %>
			&nbsp;
		<% end %>
		<%= link_to 'Daily Treatment Notes',  patient_accident_chiropractic_examination_chiropractic_treatment_path(patient, accident, chiropractic_examination, chiropractic_treatment) %>
		<% unless chiropractic_treatment.treatment_date.blank? %>
			on <%= chiropractic_treatment.treatment_date.strftime('%b %d, %Y') %>
		<% else %>
			in progress
		<% end %>	
		<% unless chiropractic_treatment.summary.blank? %>
		 - <%= chiropractic_treatment.summary %>
		<% end %>
	</td>
</tr>

app/views/accidents/_details.html.erb
<div class="span-24 non_printable_block">	
	<div class="span-24">
	
		<div class="span-6">
			<div class="span-3">
			  <label>Accident type:</label>
			</div>
			<div class="span-3 last">
			  <%= @accident.accident_type %>
			</div>
		</div>
	
		<div class="span-4">
			<div class="span-2">
			  <label>Injury date:</label>
			</div>
			<div class="span-2 last">
			  <%= @accident.injury_date %>
			</div>
		</div>
	
		<div class="span-4">
			  <%= check_box_tag :wearing_seat_belt, 1, @accident.wearing_seat_belt, :disabled => true %>&nbsp;<label>Wearing seatbelt</label>
		</div>
	
		<div class="span-4">
			  <%= check_box_tag :pedestrian, 1, @accident.pedestrian, :disabled => true %>&nbsp;<label>Pedestrian</label>
		</div>
	
		<div class="span-3">
			  <%= check_box_tag :driver, 1, @accident.driver, :disabled => true %>&nbsp;<label>Driver</label>
		</div>
	
		<div class="span-3 last">
			  <%= check_box_tag :passenger, 1, @accident.passenger, :disabled => true %>&nbsp;<label>Passenger</label>
		</div>
	
	</div>

	<hr class="space"/>

	<div class="span-24">
	
		<div class="span-6">
			<div class="span-3">
			  <label>Seating position:</label>
			</div>
			<div class="span-3 last">
			  <%= @accident.seating_position %>
			</div>
		</div>
	
		<div class="span-4">
			<%= check_box_tag :airbag_deploy, 1, @accident.airbag_deploy, :disabled => true %>&nbsp;<label>Airbag deploy</label>
		</div>

		<div class="span-4">
			<%= check_box_tag :loss_of_consciousness, 1, @accident.loss_of_consciousness, :disabled => true %>&nbsp;<label>Loss of consciousness</label>
		</div>

		<div class="span-6">
			<%= check_box_tag :lost_time_from_work, 1, @accident.lost_time_from_work, :disabled => true %>&nbsp;<label>Lost time from work</label>
			<% if @accident.lost_time_from_work? %>
				<strong>&nbsp; - &nbsp; <%= @accident.days_lost_from_work %> days </strong>
			<% end %>
		</div>
		
		<div class="span-4 last">
			<%= check_box_tag :fear_while_driving, 1, @accident.fear_while_driving, :disabled => true %>&nbsp;<label>Fear while driving</label>
		</div>
		
	</div>
	
	<hr class="space"/>
	
	<div class="prepend-6 span-24">
		<div class="span-4">
			<%= check_box_tag :taken_to_hospital, 1, @accident.taken_to_hospital, :disabled => true %>&nbsp;<label>Taken to hospital</label>
		</div>

		<div class="span-4 last">
			<%= check_box_tag :fear_while_driving, 1, @accident.fear_while_driving, :disabled => true %>&nbsp;<label>Fear while driving</label>
		</div>
	</div>

	<hr class="space"/>

	<div class="span-24">
	
		<div class="span-6">
			<div class="span-3">
			  <label>Transport mode:</label>
			</div>
			<div class="span-3 last">
			  <%= @accident.hospital_transport_mode %>
			</div>
		</div>
	
		<div class="span-4">
			<%= check_box_tag :examined, 1, @accident.examined, :disabled => true %>&nbsp;<label>Examined</label>
		</div>

		<div class="span-2">
			<%= check_box_tag :xrays, 1, @accident.xrays, :disabled => true %>&nbsp;<label>X-rays</label>
		</div>

		<div class="span-3">
			<%= check_box_tag :ctscan, 1, @accident.ctscan, :disabled => true %>&nbsp;<label>CT Scan</label>
		</div>

		<div class="span-2">
			<%= check_box_tag :mri, 1, @accident.mri, :disabled => true %>&nbsp;<label>MRI</label>
		</div>
	
		<div class="prepend-1 span-3">
			<%= check_box_tag :admitted, 1, @accident.admitted, :disabled => true %>&nbsp;<label>Admitted</label>
		</div>
	
		<div class="span-3 last">
			<%= check_box_tag :released, 1, @accident.released, :disabled => true %>&nbsp;<label>Released</label>
		</div>
	
	</div>

	<hr class="space"/>

	<div class="span-24">
		<div class="span-3">
		  <label>Hospital name:</label>
		</div>
		<div class="span-21 last">
		  <%= @accident.hospital_name %>
		</div>
	</div>

	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-3">
		  <label>Injury description:</label>
		</div>
		<div class="span-21 last">
		  <%= @accident.injury_description %>
		</div>
	</div>

	<hr class="space"/>

	<div class="span-24">
		<div class="span-3">
		  <label>Medications:</label>
		</div>
		<div class="span-21 last">
		  <%= @accident.medications %>
		</div>
	</div>

	<hr class="space"/>

	<div class="span-24">
		<div class="span-3">
		  <label>Prior injuries:</label>
		</div>
		<div class="span-21 last">
		  <%= @accident.prior_injuries %>
		</div>
	</div>

	<hr class="space"/>

	<p style="font-weight: bold;text-decoration:underline;">Prior Diagnostic Studies</p>

	<div class="span-24">
	
		<div class="span-8">
			<div class="span-1">
			  <label>MRI:</label>
			</div>
			<div class="span-7 last">
			  <%= (@accident.prior_diagnostic_study_mri_details.reject(&:blank?).join(", ")) %>
			  <% if @accident.prior_diagnostic_study_mri_details.compact.include?('Other') %>
			    <p style="font-weight: bold"><%= @accident.prior_diagnostic_study_mri_other %></p>
			  <% end %>
			</div>
		</div>
	
		<div class="span-8">
			<div class="span-2">
			  <label>CT Scan:</label>
			</div>
			<div class="span-6 last">
  			  <%= (@accident.prior_diagnostic_study_ctscan_details.reject(&:blank?).join(", ")) %>
  			  <% if @accident.prior_diagnostic_study_ctscan_details.compact.include?('Other') %>
  			     <p style="font-weight: bold"><%= @accident.prior_diagnostic_study_ctscan_other %></p>
  			  <% end %>
			</div>
		</div>
	
		<div class="span-8 last">
			<div class="span-1">
			  <label>EMG:</label>
			</div>
			<div class="span-7 last">
			  <%= (@accident.prior_diagnostic_study_emg_details.reject(&:blank?).join(", ")) %>
			</div>
		</div>
	</div>

	<hr class="space"/>

	<div class="span-24">
		<div class="span-3">
		  <label>Results:</label>
		</div>
		<div class="span-21 last">
		  <%= @accident.prior_diagnostic_results %>
		</div>
	</div>

	<hr class="space"/>

	<div class="span-24">
		<div class="span-3">
		  <label>Medical History:</label>
		</div>
		<div class="span-21 last">
		  <%= @accident.medical_history %>
		</div>
	</div>

</div>

app/views/accidents/_form.html.erb
<div class="span-24">
<%= form_for [@patient, @accident] do |f| %>
 
	<%= render "shared/error_messages", :target => @accident %>

	<div class="span-24">
		<div class="span-12">
			<div class="span-4">
			<%= f.label :accident_type %><br />
	    <%= f.select :accident_type, [['MVA', 'MVA'], ['Slip and Fall', 'Slip and Fall'], ['Work Related', 'Work Related'], ['Other', 'Other']] %>
			</div>
			<div class="span-8 last">
				<%= f.label :injury_date %><br />
		    <%= f.date_select :injury_date %>
			</div>
		</div>
		<div class="span-12 last">
			<div class="span-4">
				<br/>
				<%= f.check_box :wearing_seat_belt %> <%= f.label :wearing_seat_belt %>
			</div>
			<div class="span-2">
				<br/>
				<%= f.check_box :driver %> <%= f.label :driver %>
			</div>
				
			<div class="span-3">
				<br/>
				<%= f.check_box :passenger %> <%= f.label :passenger %>
			</div>
				
			<div class="span-3 last">
				<br/>
				<%= f.check_box :pedestrian %> <%= f.label :pedestrian %>
			</div>
		</div>
  </div>

	<hr class="space"/>
	
  <div class="span-24">
		<div class="span-12">
			<div class="span-4">
				<%= f.label :seating_position %><br/>
	    	<%= f.select :seating_position, [["Front Passenger Side", "Front Passenger Side"], ["Front Driver's Side", "Front Driver's Side"], ["Rear Passenger Side", "Rear Passenger Side"], ["Rear Middle", "Rear Middle"], ["Rear Driver's Side", "Rear Driver's Side"]], :prompt => "None" %>
			</div>
			<div class="span-4 last">
				<br/>
				<%= f.check_box :airbag_deploy %> <%= f.label :airbag_deploy %>
			</div>
		</div>
		<div class="span-12 last">
			<div class="span-4">
				<br/>
				<%= f.check_box :loss_of_consciousness %> <%= f.label :loss_of_consciousness %>
			</div>
			<div class="span-4">
				<br/>
				<%= f.check_box :lost_time_from_work %> <%= f.label :lost_time_from_work %>
				<br/>
				<% 3.times do %>
					&nbsp;
				<% end %>
				<%= f.text_field :days_lost_from_work, :class => "small_font_span_1" %> &nbsp; <label>Days</label>
	    </div>
			<div class="span-4 last">
				<br/>
				<%= f.check_box :fear_while_driving %> <%= f.label :fear_while_driving %>
	    </div>
		</div>
  </div>

	<hr class="space"/>

	<div class="span-24">
		<%= f.label :injury_description %><br />
    <%= f.text_area :injury_description, :class => 'text_area_span_23' %>
	</div>
	
	<div class="span-24">
		<div class="span-4">
			<br/>
			<%= f.check_box :taken_to_hospital %> <%= f.label :taken_to_hospital %>
		</div>
	
		<div class="span-6">
			<br/>
			<%= f.label :transport_mode %>&nbsp;
			<%= f.select :hospital_transport_mode, [['Ambulance', 'Ambulance'], ['Car', 'Car']], :prompt => "None" %>
		</div>
	
		<div class="span-12 last">
			<%= f.label :hospital_name %>&nbsp;
			<%= f.text_field :hospital_name, :class => "large_font_span_8" %>
		</div>
  </div>

	<hr class="space"/>
	
	<div class="span-24">	
		<div class="span-3">
			<%= f.check_box :examined %> <%= f.label :examined %>
		</div>
		
		<div class="span-3">
			<%= f.check_box :xrays %> <label>X-rays</label>
		</div>
		
		<div class="span-3">
			<%= f.check_box :ctscan %> <label>CT Scan</label>
		</div>
		
		<div class="span-3">
			<%= f.check_box :mri %> <label>MRI</label>
		</div>
		
		<div class="span-3">
			<%= f.check_box :released %> <%= f.label :released %>
		</div>
		
		<div class="span-3 last">
			<%= f.check_box :admitted %> <%= f.label :admitted %>
		</div>
	</div>
	
	<hr class="space"/>
		
  <div class="span-24">
    <%= f.label :medications %><br />
    <%= f.text_area :medications, :class => 'text_area_span_23' %>
  </div>

	<hr class="space"/>

  <div class="span-24">
    <%= f.label :prior_injuries %><br />
    <%= f.text_area :prior_injuries, :class => 'text_area_span_23' %>
  </div>

	<hr class="space"/>
	
	<h4>Prior Diagnostic Studies</h4>
	
	<div class="span-24">
		<div class="span-8">
			<label>MRI</label><br />
			<%= check_box_tag 'accident[prior_diagnostic_study_mri_details][]', '', true, :style => "display:none;" %>
			<% ['Cervical', 'Lumbar', 'Other'].each do |val| %>
			  <%= check_box_tag 'accident[prior_diagnostic_study_mri_details][]', val, @accident.prior_diagnostic_study_mri_details.include?(val), id: "prior_diagnostic_study_mri_details_#{val}", onChange: "toggle_other_MRI_CTScan_fields();" %>
			  <%= val %>
			<% end %>
	    <%= f.text_field :prior_diagnostic_study_mri_other, :class => 'small_font_span_4', :style => "display:none;" %>
		</div>
		<div class="span-8">
			<label> CT Scan</label><br/>
			<%= check_box_tag 'accident[prior_diagnostic_study_ctscan_details][]', '', true, :style => "display:none;" %>
			<% ['Cervical', 'Lumbar', 'Other'].each do |val| %>
			  <%= check_box_tag 'accident[prior_diagnostic_study_ctscan_details][]', val, @accident.prior_diagnostic_study_ctscan_details.include?(val), id: "prior_diagnostic_study_ctscan_details_#{val}", onChange: "toggle_other_MRI_CTScan_fields();" %>
			  <%= val %>
			<% end %>
	    <%= f.text_field :prior_diagnostic_study_ctscan_other, :class => 'small_font_span_4', :style => "display:none;" %>
		</div>
		<div class="span-8 last">
			<label>EMG</label><br />
			<%= check_box_tag 'accident[prior_diagnostic_study_emg_details][]', '', true, :style => "display:none;" %>
			<% ['Upper', 'Lower'].each do |val| %>
			  <%= check_box_tag 'accident[prior_diagnostic_study_emg_details][]', val, @accident.prior_diagnostic_study_emg_details.include?(val), id: "prior_diagnostic_study_ctscan_details_#{val}" %>
			  <%= val %>
			<% end %>
		</div>
  </div>

	<hr class="space"/>
	
  <div class="span-24">
    <%= f.label :results %><br />
    <%= f.text_area :prior_diagnostic_results, :class => 'text_area_span_23' %>
  </div>
	
	<hr class="space"/>
	
  <div class="span-24">
    <%= f.label :medical_history %><br />
    <%= f.text_area :medical_history, :class => 'text_area_span_23' %>
  </div>

	<hr class="space"/>
	
	<div class="span-24">
		<div class="span-3">
			<%= link_to 'Back', :back, :class => 'button' %>
		</div>
		<div class="prepend-17 span-3 last">
				<br/>
				<% if @accident.new_record? %>
					<%= f.submit 'Create Case' %>
				<% else %>
	    		<%= f.submit 'Update Case' %>
				<% end %>
		</div>
  </div>

<% end %>
</div>

<script type="text/javascript" charset="utf-8">
	function toggle_other_MRI_CTScan_fields() {
		var isMrChecked = $("#prior_diagnostic_study_mri_details_Other").is(':checked');
		var isCtChecked = $("#prior_diagnostic_study_ctscan_details_Other").is(':checked');
		if (isMrChecked) {
			$("#accident_prior_diagnostic_study_mri_other").show();
		} else {
			$("#accident_prior_diagnostic_study_mri_other").hide();
		}
		
		if (isCtChecked) {
			$("#accident_prior_diagnostic_study_ctscan_other").show();
		} else {
			$("#accident_prior_diagnostic_study_ctscan_other").hide();
		}
	}
	
	$(function() {
	 toggle_other_MRI_CTScan_fields();
	});
</script>

app/views/accidents/edit.html.erb
<div class="span-24">
	<ul id="crumbs">
		<li><%= link_to 'Patients', patients_path %></li>
		<li><%= link_to 'Cases', patient_accidents_path(@patient) %></li>
	</ul>
</div>

<div class="span-24">
	<div class="span-23">
		<h3>Editing Case</h3>
	</div>

	<div class="span-24">
		<%= render 'form' %>
	</div>
</div>

app/views/accidents/index.html.erb
<div class="span-24">
	<ul id="crumbs">
		<li><%= link_to 'Patients', patients_path %></li>
		<li><%= link_to 'Cases', patient_accidents_path(@patient) %></li>
	</ul>
</div>

<div class="span-24">	
	<table class="advanced">
	  <thead>
		<th class="span-4">Patient</th>
    <th class="span-3">Injury Date</th>
		<th class="span-10">Description</th>
    <th class="span-7"></th>
  </thead>

	<tbody>
		<% @accidents.each do |accident| %>
		  <tr>
		    <td><%= accident.patient.full_name %></td>
		    <td><%= accident.injury_date.strftime('%b %d, %Y') %></td>
		 		<td><%= truncate(accident.injury_description, :length => 70) %></td>
		    <td><%= link_to 'Show', patient_accident_path(@patient, accident) %> | <%= link_to 'Edit', edit_patient_accident_path(@patient, accident) %> | <%= link_to 'Archive', patient_accident_path(@patient, accident), confirm: 'Are you sure you want to archive this case? All related chiropractic examinations and chiropractic treatment notes will also be archived.', method: :delete %> | <%= link_to 'Chiropractic Examinations', patient_accident_chiropractic_examinations_path(@patient, accident) %>  </td>
		  </tr>
		
			<%= render(:partial => "chiropractic_examination", :collection => accident.chiropractic_examinations, :locals => {:patient => @patient, :accident => accident} ) %>
	
		<% end %>
	</tbody>
</table>

<hr class="space"/>

<div class="span-24">
	<%= paginate @accidents %>
</div>

<br/>

<div class="prepend-21 span-3">
<%= link_to 'New Case', new_patient_accident_path(@patient), :class => 'button positive' %>
</div>

<script>
function toggle_disclosure_triangle(element) {
  var origsrc = element.attr('src');
  var src = '';
  if (origsrc == '<%= asset_path 'triangle_right.png' %>') src = '<%= asset_path 'triangle_down.png' %>';
  if (origsrc == '<%= asset_path 'triangle_down.png' %>') src = '<%= asset_path 'triangle_right.png' %>';
  element.attr('src', src);
}
</script>

app/views/accidents/new.html.erb
<div class="span-24">
	<ul id="crumbs">
		<li><%= link_to 'Patients', patients_path %></li>
		<li><%= link_to 'Cases', patient_accidents_path(@patient) %></li>
	</ul>
</div>

<div class="span-24">
	<div class="span-23">
		<h3>New Case (<%=@patient.full_name%>)</h3>
	</div>

	<div class="span-24">
		<%= render 'form' %>
	</div>
</div>

app/views/accidents/show.html.erb
<% unless session[:current_tab] == 'Archives' %>
	<div class="span-24">
		<ul id="crumbs">
			<li><%= link_to 'Patients', patients_path %></li>
			<li><%= link_to 'Cases', patient_accidents_path(@patient) %></li>
		</ul>
	</div>
<% end %>

<% unless notice.blank? %>
	<div class="span-20 notice">
		<%= notice %>
	</div>
<% end %>

<%= render :partial => 'details' %>

<hr class="space"/>

<% if session[:current_tab] == 'Archives' %>
	<div class="span-24">
		<%= link_to 'Back', archives_accidents_path, :class => 'button' %>
	</div>
<% else %>
	<div class="span-24">
		<div class="span-3">
			<%= link_to 'Back', patient_accidents_path(@patient), :class => 'button' %>
		</div>
	
		<div class="prepend-18 span-3 last">
			<%= link_to 'Edit', edit_patient_accident_path(@patient, @accident), :class => 'button' %>
		</div>
	</div>
<% end %>