config/routes.rb
MDManage::Application.routes.draw do
  get "archives/index"
  get "archives/users"
  get "archives/clients"
  get "archives/patients"
  get "archives/accidents"
  get "archives/chiropractic_examinations"
  get "archives/chiropractic_treatments"
  get "archives/insurance_companies"
  
  get "reports/index"
  get "reports/weekly_summary"
  get "reports/monthly_summary"

  get "signup" => "users#new", :as => "signup"
  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"

  resources :insurance_companies
  
  resources :patients do
    delete "remove"
    resources :accidents do
      resources :chiropractic_examinations do
        member do
          get 'insurance_claim_processed'
          get 'print_friendly'
        end
        
        resource :chiropractic_symptom_list
        resource :chiropractic_investigation_list
        resource :chiropractic_diagnosis_list
        resource :chiropractic_treatment_plan
        resource :chiropractic_assessment
        resource :chiropractic_compliance
        
        resources :chiropractic_treatments do
          member do
            get 'insurance_claim_processed'
            get 'print_friendly'
          end
          
          resource :chiropractic_observation_list
          resource :chiropractic_body_adjustment_list
          resource :chiropractic_modalities_list
        end
      end
    end
  end

  resources :users do
    collection do
      get 'new_external'
      get 'doctor_dashboard'
    end
    
    member do
      get 'ignore_re_examination_reminders'
    end
  end
  
  resources :clients do
    member do
      get 'pending_examinations'
      get 'completed_examinations'
      get 'processed_examinations'
      get 'pending_treatments'
      get 'completed_treatments'
      get 'processed_treatments'
      get 'users'
    end
  end
  
  resources :roles
  resources :sessions
  resources :password_resets
  

  root :to => "sessions#new"

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_filter :set_current_tab
  
  def index
  end

  def weekly_summary
    if params[:start_date] && params[:end_date]
      @start_date = Date.civil(params[:start_date][:year].to_i, params[:start_date][:month].to_i, params[:start_date][:day].to_i)
      @end_date = Date.civil(params[:end_date][:year].to_i, params[:end_date][:month].to_i, params[:end_date][:day].to_i)
    else
      @start_date =  Date.current - 7.days
      @end_date =  Date.current
    end
    
    @examinations_count = ChiropracticExamination.where(:initial_examination => true, :insurance_claim_filed_at => @start_date..@end_date + 1.day).count
    @re_examinations_count = ChiropracticExamination.where(:initial_examination => false, :insurance_claim_filed_at => @start_date..@end_date + 1.day).count
    @treatments_count = ChiropracticTreatment.where(:insurance_claim_filed_at => @start_date..@end_date).count
  end

  def monthly_summary
    if params[:date] && params[:date][:month] && params[:date][:year]
      @month = params[:date][:month].to_i
      @year = params[:date][:year].to_i
    else
      @month = Date.current.month
      @year = Date.current.year
    end
    
    @start_date = Date.civil(@year, @month, 1)
    @end_date = @start_date.end_of_month
    
    @examinations_count = ChiropracticExamination.where(:initial_examination => true, :insurance_claim_filed_at => @start_date..@end_date + 1.day).count
    @re_examinations_count = ChiropracticExamination.where(:initial_examination => false, :insurance_claim_filed_at => @start_date..@end_date + 1.day).count
    @treatments_count = ChiropracticTreatment.where(:insurance_claim_filed_at => @start_date..@end_date).count
  end

  private
  
  def set_current_tab
    session[:current_tab] = 'Reports'
  end
  
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/index.html.erb
<div class="span-24">
	
	<table class="advanced">
	  <thead>
	    <th class="span-24">Report Title</th>
    </thead>
	
		<tbody>
			<tr><td><%= link_to 'Weekly Summary Report', reports_weekly_summary_path %></td></tr>
			<tr><td><%= link_to 'Monthly Summary Report', reports_monthly_summary_path %> </td></tr>
		</tbody>
	</table>
	
</div>

app/views/reports/monthly_summary.html.erb
<%= form_tag reports_monthly_summary_path, :method => 'get' do %>
	<div class="span-24">
		<div class="span-2">
			<label>Month:</label>
		</div>
		<div class="span-4">
			<%= select_month @month %>
		</div>
		<div class="span-2">
			<label>Year:</label>
		</div>
		<div class="span-3">
			<%= select_year @year %>
		</div>
		<div class="span-3 last">
			<%= submit_tag 'Show' %>
		</div>
	</div>
<% end %>

<hr class="space"/>

<div class="span-24">
	
	<table class="advanced">
	  <thead>
	    <th class="span-6">Medical Claim Type</th>
			<th class="span-18 last">Total Count</th>
    </thead>
	
		<tr>
			<td>Examinations</td>
			<td><%= @examinations_count %></td>
		</tr>
		<tr>
			<td>Re-examinations</td>
			<td><%= @re_examinations_count %></td>
		</tr>
		<tr>
			<td>Daily Treatments</td>
			<td><%= @treatments_count %></td>
		</tr>
	</table>
	
</div>

<div class="span-24">
	<%= link_to 'Back', reports_index_path, :class => 'button' %>
</div>

app/views/reports/weekly_summary.html.erb
<%= form_tag reports_weekly_summary_path, :method => 'get' do %>
	<div class="span-24">
		<div class="span-2">
			<label>Start Date:</label>
		</div>
		<div class="span-6">
			<%= select_date @start_date,:prefix => :start_date %>
		</div>
		<div class="span-2">
			<label>End Date:</label>
		</div>
		<div class="span-6">
			<%= select_date @end_date, :prefix => :end_date %>
		</div>
		<div class="span-3 last">
			<%= submit_tag 'Show' %>
		</div>
	</div>
<% end %>

<hr class="space"/>

<div class="span-24">
	
	<table class="advanced">
	  <thead>
	    <th class="span-6">Medical Claim Type</th>
			<th class="span-18 last">Total Count</th>
    </thead>
	
		<tr>
			<td>Examinations</td>
			<td><%= @examinations_count %></td>
		</tr>
		<tr>
			<td>Re-examinations</td>
			<td><%= @re_examinations_count %></td>
		</tr>
		<tr>
			<td>Daily Treatments</td>
			<td><%= @treatments_count %></td>
		</tr>
	</table>
	
</div>

<div class="span-24">
	<%= link_to 'Back', reports_index_path, :class => 'button' %>
</div>